# Generated by Django 4.1.7 on 2023-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0002_chat_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="namespace",
            field=models.CharField(default="test", max_length=300),
            preserve_default=False,
        ),
    ]
