# Generated by Django 4.1.7 on 2023-04-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0003_chat_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_key",
            field=models.BooleanField(default=False),
        ),
    ]
