# Generated by Django 4.1.7 on 2023-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayushma", "0003_chat_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="allow_key",
            field=models.BooleanField(default=False),
        ),
    ]
