# Generated by Django 4.1.7 on 2023-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0004_user_allow_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
