# Generated by Django 4.1.7 on 2023-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0007_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
