# Generated by Django 4.1.7 on 2023-04-25 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0008_alter_document_description_alter_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="user",
            new_name="creator",
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
