# Generated by Django 4.1.7 on 2023-04-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0009_rename_user_project_creator_project_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="prompt",
            field=models.TextField(default=""),
        ),
    ]
