# Generated by Django 4.1.7 on 2023-04-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0010_project_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="namespace",
        ),
        migrations.AddField(
            model_name="chat",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="ayushma.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
