# Generated by Django 4.1.7 on 2023-04-25 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0011_remove_chat_namespace_chat_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
    ]
