# Generated by Django 4.1.7 on 2023-04-30 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0005_resetpasswordtoken"),
        ("ayushma", "0012_remove_project_users"),
    ]

    operations = []
