# Generated by Django 4.1.7 on 2023-05-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0014_document_document_type_document_text_content_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql="UPDATE ayushma_document SET document_type = 1"),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.IntegerField(
                choices=[(1, "File"), (2, "Url"), (3, "Text")], default=1
            ),
        ),
    ]
