# Generated by Django 4.1.7 on 2023-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0015_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="language_code",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
