# Generated by Django 4.1.7 on 2023-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0015_alter_document_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reference_documents",
            field=models.ManyToManyField(blank=True, to="ayushma.document"),
        ),
    ]
