# Generated by Django 4.1.7 on 2023-05-14 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0016_chat_language_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="language_code",
            new_name="language",
        ),
    ]
