# Generated by Django 4.1.7 on 2023-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0017_rename_language_code_chat_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
