# Generated by Django 4.1.7 on 2023-05-17 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0016_chatmessage_reference_documents"),
        ("ayushma", "0019_remove_chatmessage_audio_and_more"),
    ]

    operations = []
