# Generated by Django 4.1.7 on 2023-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0020_remove_document_file_document_s3_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="reference_documents",
            field=models.ManyToManyField(blank=True, to="ayushma.document"),
        ),
    ]
