# Generated by Django 4.1.7 on 2023-05-21 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0020_migrate_language_field"),
        ("ayushma", "0020_remove_document_file_document_s3_url"),
    ]

    operations = []
