# Generated by Django 4.1.7 on 2023-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0020_merge_20230517_1022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
        migrations.AddField(
            model_name="document",
            name="s3_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
