# Generated by Django 4.1.7 on 2023-05-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0021_chatmessage_reference_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="translated_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
