# Generated by Django 4.1.7 on 2023-05-26 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0021_chatmessage_reference_documents"),
        ("ayushma", "0021_merge_20230521_2146"),
    ]

    operations = []
