# Generated by Django 4.2.1 on 2023-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0023_chatmessage_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="top_k",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
