# Generated by Django 4.2.1 on 2023-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0025_chat_prompt_alter_chat_project_alter_chat_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="s3_url",
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
