# Generated by Django 4.2.1 on 2023-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0026_remove_document_s3_url_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="ayushma_audio_url",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
