# Generated by Django 4.1.7 on 2023-06-13 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0027_remove_chatmessage_ayushma_audio_url_and_more"),
        ("ayushma", "0027_testquestion_testsuite_testrun_testresult_and_more"),
    ]

    operations = []
