# Generated by Django 4.2.1 on 2023-06-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0028_merge_20230613_1346"),
        ("ayushma", "0028_project_stt_engine"),
    ]

    operations = []
