# Generated by Django 4.2.1 on 2023-06-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0029_merge_20230621_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="noonce",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "Hallucinating"),
                    (2, "Wrong"),
                    (3, "Unsatisfactory"),
                    (4, "Satisfactory"),
                    (5, "Good"),
                    (6, "Excellent"),
                ]
            ),
        ),
    ]
