# Generated by Django 4.2.1 on 2023-07-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0030_chatmessage_noonce_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="model",
            field=models.IntegerField(
                choices=[
                    (1, "Gpt 3 5"),
                    (2, "Gpt 3 5 16K"),
                    (3, "Gpt 4"),
                    (4, "Gpt 4 32K"),
                ],
                default=1,
            ),
        ),
    ]
