# Generated by Django 4.2.1 on 2023-06-27 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0030_chatmessage_noonce_alter_feedback_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("liked", models.BooleanField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ayushma.chatmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
