# Generated by Django 4.2.1 on 2023-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0030_chatmessage_noonce_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="references",
            field=models.ManyToManyField(blank=True, to="ayushma.document"),
        ),
    ]
