# Generated by Django 4.2.1 on 2023-07-11 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0031_project_model"),
        ("ayushma", "0031_testresult_references"),
    ]

    operations = []
