# Generated by Django 4.2.1 on 2023-07-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0032_merge_0031_project_model_0031_testresult_references"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
