# Generated by Django 4.2.1 on 2023-07-31 12:00

from django.db import migrations, models

from ayushma.models.enums import StatusChoices


def migrate_testrun_status(apps, schema_editor):
    TestRun = apps.get_model("ayushma", "TestRun")
    for testrun in TestRun.objects.all():
        if testrun.complete:
            testrun.status = StatusChoices.COMPLETED
        else:
            testrun.status = StatusChoices.CANCELED
        testrun.save()


def reverse_testrun_status(apps, schema_editor):
    TestRun = apps.get_model("ayushma", "TestRun")
    for testrun in TestRun.objects.all():
        if testrun.status == StatusChoices.COMPLETED:
            testrun.complete = True
        else:
            testrun.complete = False
        testrun.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0033_project_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testrun",
            name="complete",
        ),
        migrations.AddField(
            model_name="testrun",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Running"),
                    (2, "Completed"),
                    (3, "Canceled"),
                    (4, "Failed"),
                ],
                default=1,
            ),
        ),
    ]
