# Generated by Django 4.2.1 on 2023-07-31 14:07

from django.db import migrations

from ayushma.models.enums import StatusChoices


def migrate_testrun_status(apps, schema_editor):
    TestRun = apps.get_model("ayushma", "TestRun")
    for testrun in TestRun.objects.all():
        if testrun.status == StatusChoices.RUNNING:
            testrun.status = StatusChoices.COMPLETED
        testrun.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0034_remove_testrun_complete_testrun_status"),
    ]

    operations = [
        migrations.RunPython(migrate_testrun_status),
    ]
