# Generated by Django 4.2.1 on 2023-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0036_alter_apikey_creator_temptoken_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temptoken",
            name="token",
            field=models.CharField(max_length=256),
        ),
    ]
