# Generated by Django 4.2.1 on 2023-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0037_alter_temptoken_token"),
        ("ayushma", "0037_chat_model"),
    ]

    operations = []
