# Generated by Django 4.2.1 on 2023-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0038_merge_0037_alter_temptoken_token_0037_chat_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploading",
            field=models.BooleanField(default=True),
        ),
    ]
