# Generated by Django 4.2.1 on 2023-08-31 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0039_alter_document_uploading"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="preset_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, null=True, size=100
            ),
        ),
    ]
