# Generated by Django 4.2.1 on 2023-09-04 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0040_project_open_ai_key"),
        ("ayushma", "0040_project_preset_questions"),
    ]

    operations = []
