# Generated by Django 4.2.1 on 2023-09-05 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0031_chatfeedback"),
        ("ayushma", "0041_merge_20230904_0908"),
    ]

    operations = []
