# Generated by Django 4.2.1 on 2023-09-05 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0042_alter_project_preset_questions"),
        ("ayushma", "0042_merge_0031_chatfeedback_0041_merge_20230904_0908"),
    ]

    operations = []
