# Generated by Django 4.2.5 on 2023-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayushma', '0043_merge_20230905_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stt_engine',
            field=models.IntegerField(choices=[(1, 'Whisper'), (2, 'Google'), (3, 'Self Hosted')], default=1),
        ),
    ]
