# Generated by Django 4.2.1 on 2023-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0044_alter_project_stt_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="testrun",
            name="references",
            field=models.BooleanField(default=True),
        ),
    ]
