# Generated by Django 4.2.5 on 2023-10-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0046_testquestion_attachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testquestion",
            old_name="attachments",
            new_name="documents",
        ),
        migrations.AddField(
            model_name="document",
            name="test_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ayushma.testquestion",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ayushma.project",
            ),
        ),
    ]
