# Generated by Django 4.2.5 on 2023-10-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0047_rename_attachments_testquestion_documents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="model",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Gpt 3 5"),
                    (2, "Gpt 3 5 16K"),
                    (3, "Gpt 4"),
                    (4, "Gpt 4 32K"),
                    (5, "Gpt 4 Visual"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="model",
            field=models.IntegerField(
                choices=[
                    (1, "Gpt 3 5"),
                    (2, "Gpt 3 5 16K"),
                    (3, "Gpt 4"),
                    (4, "Gpt 4 32K"),
                    (5, "Gpt 4 Visual"),
                ],
                default=1,
            ),
        ),
    ]
