# Generated by Django 4.2.6 on 2023-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0048_alter_chat_model_alter_project_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="thread_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="assistant_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
