# Generated by Django 4.2.6 on 2024-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0050_alter_chat_model_alter_project_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tts_engine",
            field=models.SmallIntegerField(
                choices=[(1, "openai"), (2, "google")], default=2
            ),
        ),
    ]
