# Generated by Django 4.2.6 on 2024-02-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0050_alter_chat_model_alter_project_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tts_engine",
            field=models.IntegerField(
                choices=[(1, "Openai"), (2, "Google")], default=2
            ),
        ),
    ]
