# Generated by Django 4.2.6 on 2024-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ayushma", "0051_project_tts_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="failed",
            field=models.BooleanField(default=False),
        ),
    ]
