#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [[ -n "${GOOGLE_APPLICATION_CREDENTIALS_B64:-}" ]]; then
    echo "${GOOGLE_APPLICATION_CREDENTIALS_B64}" | base64 -d > gc_credential.json
fi

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
/usr/local/bin/gunicorn core.wsgi --bind 0.0.0.0:5000 --timeout 180 --chdir=/app
