#!/bin/bash

set -o errexit
set -o nounset


rm -f './celerybeat.pid'
watchmedo \
    auto-restart --directory=./ --pattern=*.py --recursive -- \
    celery --workdir="/app" -A core.celery_app beat --loglevel=INFO
